### ISSUE TITLE
Addition of BIP49 and BIP84 derivation paths broke aezeed

### ISSUE THREAD

**Issue by jan386** [guggero/cryptography-toolkit#1]
When generating (or importing) aezeed seeds it used to be possible to obtain the root xpriv like this (expected behviour):
![obrazek](https://user-images.githubusercontent.com/52366922/60392645-98137880-9b07-11e9-9137-2f1c2d47df5b.png)

Now, the drop-down menu of the Base58 xpriv shows nothing and, correspondingly, the xpriv is not generated (current behaviour):
![obrazek](https://user-images.githubusercontent.com/52366922/60392663-e45eb880-9b07-11e9-99df-4e81c49887c7.png)
 
Since I used this tool just last week successfully, I believe that this undesired behaviour was caused by the recent addition of two new derivation paths.

Steps to reproduce expected behaviour:
1. Download release 1.1.0 of the toolkit, extract it and open PATH/cryptography-toolkit.offline/index.html#!/aezeed
2. Generate a random aezeed mnemonic
3. Observe HD node root key being generated.

Steps to reproduce current behaviour:
1. Go to https://guggero.github.io/cryptography-toolkit/#!/aezeed
2. Generate a random aezeed mnemonic
3. Observe HD node root key not being generated.

**Comment by guggero** [comment]
Thank you very much for reporting this!
I did some refactoring to test something out and was a bit in a hurry. Should've tested it better.
It's fixed with 76b45c0715a0c8b8055320ac1c2b7ada25885ef3
