### ISSUE TITLE
Adding xpubs at derivation-path-level extended keys

### ISSUE THREAD

**Issue by vindard** [guggero/cryptography-toolkit#12]
## Description

I was working through comparing derivation paths and keys from my lnd (regtest) setup against what's generated with this toolkit and couldn't find an easy way to get to the xpub that's shown at ` $ lncli wallet accounts list --address_type p2wkh`. Would it be possible to add that in like below?

![New Project](https://user-images.githubusercontent.com/17693119/234807269-0cfeb03f-48b3-4391-ad71-95fb2205cea1.png)

**Comment by guggero** [comment]
Good idea, added! Might need to do a hard reload of the page to clear all caches.

Here's the example for getting the account as described in `lnd`'s `docs/remote-signing.md` file:
![Screenshot from 2023-04-27 13-57-35](https://user-images.githubusercontent.com/1008879/234855542-d8692b75-4f78-41f9-8083-c54ae9e3f037.png)
