### ISSUE TITLE
[Add feature] Add more WIF key import options for other wallets and scripts

### ISSUE THREAD

**Issue by jonjonez** [guggero/cryptography-toolkit#13]
IN "Import parameters:", "Import type" add conversion to import with descriptors in bitcoin core: ex:

importdescriptors '[{"desc":"wpkh(L4p2b9VAf8k5aUahF1JCJUzZkgNEAqLfq8DDdQiyAprQAKSbu8hf)#vppj2c9k","timestamp":"now"}]'

I suggest also adding the type of script (combo, pkh, sh(wpkh, wpkh, tr)) somewhere to import into the bitcoin core descriptor.

Because the "importprivkey" command will fall into disuse due to the new type of bitcoin core descriptor wallet no longer accepting these commands (importprivkey, dumprivkey, importwallet, dumpwallet...).

I also suggest adding the import types accepted by the electrum wallet:

p2wpkh:L4p2b9VAf8k5aUahF1JCJUzZkgNEAqLfq8DDdQiyAprQAKSbu8hf
p2pkh:L4p2b9VAf8k5aUahF1JCJUzZkgNEAqLfq8DDdQiyAprQAKSbu8hf
p2wpkh-p2sh:L4p2b9VAf8k5aUahF1JCJUzZkgNEAqLfq8DDdQiyAprQAKSbu8hf

**Comment by guggero** [comment]
Hi. Thanks for the issue. You are correct, this toolkit is quite outdated.
I didn't really plan on updating it, as it's mostly a hobby side project.
Depending on what you want to achieve, you might want to look into [`chantools`](https://github.com/lightninglabs/chantools) which has the [`genimportscript`](https://github.com/lightninglabs/chantools/blob/master/doc/chantools_genimportscript.md) sub command that supports the Electrum types.

There is no support for descriptor wallets there yet either, but the chance of me adding them there are actually greater than in this project. So feel free to open the same issue in that repo.

**Comment by jonjonez** [comment]
I really liked your project and I think it is really necessary for key recovery, iancoleman is no longer being updated, sad.

If you can keep this project updated for the good of the community it will be very rewarding.

**Comment by guggero** [comment]
Added Electrum and basic `wpkh` descriptor support to the wallet import functionality.
Unfortunately there is no usable JavaScript descriptor library out there yet that supports P2TR, so I'm going to add Taproot support at a later date.
