### ISSUE TITLE
aezeed root key not updating when entropy changes

### ISSUE THREAD

**Issue by iancoleman** [guggero/cryptography-toolkit#9]
Great tool thanks.

In the [aezeed tool](https://guggero.github.io/cryptography-toolkit/#!/aezeed), the `HD node root key base58` value does not update as expected when the entropy is changed.

Steps to reproduce:

1. load the page and record the root key
1. change the `Entropy` value using the keyboard (not the `Randomize entropy` button)
1. note the mnemonic has changed but the root key has not (expect that the root key should change)
1. change dropdown for the root key from `btc legacy` to any other value, then back to `btc legacy`
1. note the root key is now different to the one in the first step (this root key should be shown in step 3 but is not)

**Comment by guggero** [comment]
Thanks for the report, fixed it in 0ae1fdc.
